### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by hypercube-software** [devlauer/plantuml-generator#105]
Unfortunately I can't show you the code I'm working on but what I saw is the following:

`PlantUMLSequenceDiagramGenerator.getCallerMethod` can run in a infinite loop.

getCallerMethod => instrument => getCallerMethod  => instrument => getCallerMethod ...

Some kind of check should be done to prevent this. 
I will try to download the source code of your plugin to see what's going on...

**Comment by devlauer** [comment]
Thank you for reporting this bug. 
You are right, there was a bug in the sequence diagram generator if you use recursive or circular method calls. 
I've added two tests for these two use cases and fixed the bug in version 2.2.4. 
This version should be available in the next 2-4 hours on maven central. 

If you are still getting a StackOverflowError with this new version, please reopen the issue and give me some hints on your code. Thank you!
