### ISSUE TITLE
Add cardinality for class diagram

### ISSUE THREAD

**Issue by Maxouwell** [devlauer/plantuml-generator#108]
Hello !

First let me congratulate you for this fantastic tools.

Sorry if I missed it, but is there a way to add precise cardinality on class ?

To be more precise allow to transform this :
![image](https://github.com/devlauer/plantuml-generator/assets/13748802/634700e6-51d9-4791-ba69-9d6efb417563)
to this :
![image](https://github.com/devlauer/plantuml-generator/assets/13748802/fd3e45d1-52fa-4020-8cea-cd8dfafc7b29)
ideally with an annotation on the class.

Thanks !

**Comment by devlauer** [comment]
No you are missing nothing. Currently there is no possibility to define the cardinality more precisely. I generally try to use standard classes from Standard Java or Java EE or Jakarta EE (currently only before version 9 with the old namespace) for the analysis. There I personally wouldn't know of any corresponding annotation to define that. 
But maybe it would be an option to create a separate module in which I provide appropriate annotations with which you can specify the cardinality. But this would also have the disadvantage that you would then pull a dependency on this library into your own code.
In any case, it would probably take me a while to get to that.

**Comment by Maxouwell** [comment]
What about [javax.validation.constraints.Size](https://jakarta.ee/specifications/platform/8/apidocs/javax/validation/constraints/size) ?

It's in Java EE, has a min and a max and is semanticaly valid for this.

Skimming through the code it's seems not so hard to implement, and I may be able to do a PR for it.
What do you think ?

**Comment by Maxouwell** [comment]
(NotEmpty could also serve as a 1..*)

**Comment by devlauer** [comment]
That's right, I didn't think of Size and NotEmpty as annotations. These would indeed fit well. If you open a PR for it, I would appreciate it.

**Comment by devlauer** [comment]
Looks good. First time someone has added documentation right away. Thanks for your effort! 
I will release the new feature in the next hours. 

Regarding your comment in the ClassAnalyzer about the necessary if-statement: you are right, I will adjust that for the next release.

**Comment by devlauer** [comment]
The release is out now. Depending on the distribution among the maven central servers it should be available in the next 2 hours.
Therefore i am closing this issue.
