### ISSUE TITLE
Difference between `remove...` and `hide...` properties

### ISSUE THREAD

**Issue by lrkwz** [devlauer/plantuml-generator#22]
I wonder what is the difference between `hideFields` and `removeFields` properties (same for hide and remove methods).

**Comment by devlauer** [comment]
```hideFields``` just adds the ```hide fields``` command to the diagram text, but the fields are still part of that text. 
```removeFields``` does not add any field to the diagram text.
Same with methods.
Hopefully this answers your question. 
I've also added the same description to the README.

**Comment by lrkwz** [comment]
Thank you
