### ISSUE TITLE
Add more JPA annotations

### ISSUE THREAD

**Issue by lrkwz** [devlauer/plantuml-generator#23]
I think that #8 should be completed with:

* javax.persistence.MappedSuperClass
* javax.persistence.Index (because it can express unique constraints which are quite meaningful at class level view)
* javax.persistence.UniqueConstraint

**Comment by devlauer** [comment]
I can add MappedSuperClass without any problem. But I am not sure how to model javax.persistence.Index and UniqueConstraint in UML correctly because they are part of the database model (you use columnnames not fieldnames). 
Do you have some examples how you would expect them to be generated in the Plant UML diagram?

**Comment by devlauer** [comment]
I thought about it and tagged values are perhaps a good representation for these two annotations. Unlikely PlantUML does not allow them to be added to the class compartment with the standard commands so adding them to a separat compartment could be a solution. It should look like this example:
![RP11Qy9048NFpQyOFBLKWwOt4H5C3e6UgWUXzh3kJjk1pMoRdO0IyjyT4wKKdClCutjl6CPw4oCuJD6pgIbmAXWbTQ4ofFDqcitIRN015ek2XUIqN0AqoKCRxJTM1YxkOUmW0QrMpC4Zcmf1DDUhRY343eyOzxoNIwoN0Eys-ARYsNZesSS_djruTkKlog_x6gRV1ctWABLUA_tcF](https://user-images.githubusercontent.com/3578132/160484033-c515ce70-5f75-46dc-b487-07585e6c95d5.png)

Is this a possible solution for your problem?

**Comment by lrkwz** [comment]
Yes, looks perfect

**Comment by devlauer** [comment]
I have implemented in the next version (1.4.1). It is released and should be available on maven central within the next 2 hours. I have changed the tagged values a little bit to be more generic:

![ZP0nQyD038Nd-bTeJAbZqeubpb9IC8HEwUHaK7DAEBZJ9IUvr1Z_zrukb9QGeTkJ-AJtf9r34J1KaMECDd2b95gPuD4cFPizFLQlwwK_kj0JmNo-PBNQBnQGz1e_79tbKC2GYuODVP7K6zverZ3fs9uwgbkD7MtBNN2TvvKLhLj1Xn7xalonCLkulp6qHoTNKvyK9UNC_FZZ-vxvb](https://user-images.githubusercontent.com/3578132/160665130-296aaeca-3217-412e-971a-fb8151d05aba.png)

**Comment by devlauer** [comment]
Hopefully everything is fine now. So I am closing this ticket. Feel free to reopen it if the issue still exists for you. Thank you.
