### ISSUE TITLE
Feature-Request: black and white lists with regex patterns

### ISSUE THREAD

**Issue by andrehertwig** [devlauer/plantuml-generator#4]
Hi
If you have big packages or many packages to generate, there could be a long list of class name exclusions.
So maybe it would be usefull to have a regex based white list (inclusion) for classes (and as new feature for attributes and methodnames) and black list (exclusion). 
The whitelist should has a higher precedence than the blacklist because if a whitelist is maintained a blacklist makes no sense.

KR André

**Comment by devlauer** [comment]
Hi André,

I already had the same problem as you in one case with to many classes to exclude and thought of it as a new feature (I only thought of a blacklist). So I will have a look on it for the next version.

Kind regards
M.
