### ISSUE TITLE
Request for similar feature as useShortClassNames in class diagram

### ISSUE THREAD

**Issue by nunocruz** [devlauer/plantuml-generator#41]
The class diagram has an out of the box feature to remove `java.lang` from class names, but I would like a similar feature for my own classes. 

The generated UML ends up having very long method descriptions, because if I am using my own objects as a parameter, the full path is shown rather than just the class name.

**Comment by devlauer** [comment]
Hi,

I've added a new feature to the utility and to the maven project to shorten the class names in the class diagram at all (useShortClassNames) or only in fields and methods (useShortClassNamesInFieldsAndMethods). This feature will be part of the next release. Have a look into the latest documentation if these to new configuration toggles fit your needs:

* Utility
  * https://devlauer.github.io/plantuml-generator/plantuml-generator-util/latest/class-diagram/config/use-short-classnames.html
  * https://devlauer.github.io/plantuml-generator/plantuml-generator-util/latest/class-diagram/config/use-short-classnames-in-fields-and-methods.html
* Maven Plugin
  * https://devlauer.github.io/plantuml-generator/plantuml-generator-maven-plugin/latest/class-diagram/config/use-short-classnames.html
  * https://devlauer.github.io/plantuml-generator/plantuml-generator-maven-plugin/latest/class-diagram/config/use-short-classnames-in-fields-and-methods.html

If they do I'll release the version as soon as possible.

**Comment by nunocruz** [comment]
This fits exactly my needs! 

I will keep an eye for the release, thank you!

**Comment by devlauer** [comment]
Sorry for the delay, but I only got to it now! 
I've released the new version. It should be publicly available within the new 2 hours.

**Comment by nunocruz** [comment]
No worries.
Thank you so much for this!
