### ISSUE TITLE
Creating puml-file for all modules of a maven reactor build

### ISSUE THREAD

**Issue by arauchberger** [devlauer/plantuml-generator#6]
Hi,
i wonder if there would be a way to create a puml for all modules on the build-classpath (filtered as already possible, e.g. via scanPackage) to get one big puml for the whole product-build.

currently i get a puml per module, so i can not visualise class-dependencies between modules/projects.

thanks

**Comment by devlauer** [comment]
Hi,

it is already possible to create a plantuml class diagram over multiple modules in a multi module project and even over all referenced dependencies. The maven plugin uses the same classloader as it is used for the build process (during compilation). So all classes in the compile/build classpath are scanned. The classes inside the diagram depend only on your scanPackages, whitelistRegexp or blacklistRegexp parameters.

Please have a look on my sample repository https://github.com/devlauer/sample.asciidoc which i use for different asciidoc and plantuml samples. It is a multimodule project with three modules (project1, project2, project3). Inside module project1 there are 5 classes (BaseDomainClass, ChildA, ChildB, DomainInterface, UtilClass) in the package de.elnarion.sample.domain plus 1 class in another package. Inside module project2 there is only 1 class (TestProject2 in package de.elnarion.sample.domain2) referencing BaseDomainClass and ChildA from project1. 
In project2 i've added the plantuml-generator-maven-plugin to the build to generate a diagram which consists of all classes within the packages de.elnarion.sample.domain and de.elnarion.sample.domain2. And after the build is run all of them are inside the diagram although they are in different modules. Just clone the repository and run mvn install. Afterwards have a look on the file project2/target/generated-docs/testdiagram1.adoc.

Hopefully this helps! If not an example would be nice.

Kind regards

**Comment by arauchberger** [comment]
Hi,

i do have a reactor-pom in fhirstore-main which i execute when building:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>at.pineit.fhirstore</groupId>
    <artifactId>fhirstore-main</artifactId>

    <version>1.0.0</version>

    <packaging>pom</packaging>

    <description>creating netty based fhirstore microservice</description>

    <modules>
        <module>../fhirstore-build</module>
        <module>../fhirstore-core</module>
        <module>../fhirstore-logic</module>
        <module>../fhirstore-storage</module>
        <module>../fhirstore-soap-client</module>
        <module>../fhirstore-soap-server</module>
        <module>../fhirstore-netty</module>
        <!-- currenty unused, and failing CI on gitHub
            <module>../fhirstore-db</module>
        -->
    </modules>

    <build>

        <plugins>

            <!--
                plantuml-generator: creates a puml file in target/generated-docs folder
            -->
            <plugin>
                <artifactId>plantuml-generator-maven-plugin</artifactId>
                <groupId>de.elnarion.maven</groupId>
                <version>1.1.2</version>
                <executions>
                    <execution>
                        <id>generate-class-dependency-puml</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <outputFilename>${project.artifactId}-class-dependency.puml</outputFilename>
                            <scanPackages>
                                <scanPackage>
                                    at.pineit.fhirstore
                                </scanPackage>
                            </scanPackages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

the fhirstore-build only holds a parent-pom for all the other projects for common things. this is where i added your plugin as well, so i get a puml per project.

now i have added what you see in the reactor-pom, but i only get the following error:

```
[INFO] -----------------< at.pineit.fhirstore:fhirstore-main >-----------------
[INFO] Building fhirstore-main 1.0.0                                      [8/8]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fhirstore-main ---
[INFO] 
[INFO] --- plantuml-generator-maven-plugin:1.1.2:generate (generate-class-dependency-puml) @ fhirstore-main ---
[INFO] Starting plantuml generation 
[ERROR] Exception:No classes found for package at.pineit.fhirstore
[ERROR] 
java.lang.ClassNotFoundException: No classes found for package at.pineit.fhirstore
    at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGenerator.getAllClassesInScanPackages (PlantUMLClassDiagramGenerator.java:806)
    at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGenerator.getAllDiagramClasses (PlantUMLClassDiagramGenerator.java:770)
    at de.elnarion.util.plantuml.generator.PlantUMLClassDiagramGenerator.generateDiagramText (PlantUMLClassDiagramGenerator.java:164)
    at de.elnarion.maven.plugin.plantuml.generator.PlantUMLGeneratorMojo.execute (PlantUMLGeneratorMojo.java:162)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by devlauer** [comment]
Hi,

now I see your problem. You've created a reactor/multimodule project where all modules reference the parent pom. In this case the parent project (fhirstore.main) is build before all modules (which depend on the parent). But the parent pom is of type pom and has no dependencies. So there is no compile classloader for this project (because of type pom) and even if there would be any (e.g. if you choose jar as type) it would find no classes because there are no dependencies in the parent project and there are no classes in the project itself.
If you want to create a diagram of all classes of all modules, you should take one of the modules which depends on all other modules and put the plugin configuration in there. If there is no such module, you could create a separate module which depends on all the others (is of type jar) and put the plugin configuration in there. You could call this separate module perhaps fhirstore.docs.

If you still want to have a diagram for each module, you could create a separate profile in your parent pom and put the plugin configuration in there. This profile should not be active by default, because it should not be run in the parent project itself. But you could activate this profile in each module with a marker file or a special property. But be careful if one of the modules depends on another module (e.g. fhirstore.logic depends on fhirstore.core) the diagram of this module would contain the classes of both modules because both are in the compile classpath. A separation would only be possible with special whitelistRegexp, blacklistRegexp or differen packages. But therefore you need to make a plugin configuration in the dependant module (in this example fhirstore.logic).

Hopefully this explanation helps! If not, i could provide a sample project for your special constellation, but this takes some time.

Kind Regards

**Comment by arauchberger** [comment]
Hi,

thanks for the detailed support.
i see the issue with the "no classes found" for non-jar-modules - thanks for pointing that out.

actually i do have the plantuml-generator-maven-plugin configured in the fhirstore-main (which is the parent pom for the others) and so every module get's it's own puml for it's own classes/packages.

when i create such a fhirstore-docs module (jar) adding all others as dependencies and adding your plugin i also only get a puml for this project (no classes of other modules are listed). i assume this is the same as i already have for the fhirstore-netty, which is somehow the main-module.

the pom.xml of fhirstore-docs
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>at.pineit.fhirstore</groupId>
    <artifactId>fhirstore-docs</artifactId>
    <version>1.0.0</version>

    <name>fhirstore-docs</name>

    <packaging>jar</packaging>


    <dependencies>
        <!-- pineIT project dependencies -->
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-db</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-logic</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-netty</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-soap-client</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-soap-server</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>at.pineit.fhirstore</groupId>
            <artifactId>fhirstore-storage</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>


    <build>

        <plugins>

            <!--
                plantuml-generator: creates a puml file in target/generated-docs folder
            -->
            <plugin>
                <artifactId>plantuml-generator-maven-plugin</artifactId>
                <groupId>de.elnarion.maven</groupId>
                <version>1.1.2</version>
                <executions>
                    <execution>
                        <id>generate-class-dependency-puml</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <outputFilename>${project.artifactId}-class-dependency.puml</outputFilename>
                            <scanPackages>
                                <scanPackage>
                                    at.pineit.fhirstore
                                </scanPackage>
                            </scanPackages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>de.elnarion.maven</groupId>
                                        <artifactId>plantuml-generator-maven-plugin</artifactId>
                                        <versionRange>[1.1.2,)</versionRange>
                                        <goals>
                                            <goal>generate</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

the resulting puml:

```
@startuml

interface at.pineit.fhirstore.package-info {
}

@enduml
```

**Comment by arauchberger** [comment]
what i have discovered in the meanwhile is that there is a docket for java doc that is using plantumb as well and i get a java doc containing package-dep.-diags., class-dep.-diags. and class-drags.

this solves the issue i have.

here is the profile i added to my fhirstore-build (parent-pom) using the doclet

```
        <profile>
            <id>aggregate-javadoc</id>
            <activation>
                <file>
                    <exists>${product.trigger.filename}</exists>
                </file>
            </activation>
              <build>
                <plugins>
                    <!--
                        Javadoc
                    -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.2.0</version>
                        <configuration>
                            <skip>${javadoc.skip}</skip>
                            <failOnError>false</failOnError>
                            <quiet>${javadoc.quiet}</quiet>
                            <javadocExecutable>${javadoc.bin}</javadocExecutable>
                            <show>private</show>

                            <!-- include dependency-sources of other pineIT projects -->
                            <includeDependencySources>true</includeDependencySources>
                            <includeTransitiveDependencySources>true</includeTransitiveDependencySources>
                            <dependencySourceIncludes>
                                <dependencySourceInclude>${project.groupId}:*</dependencySourceInclude>
                            </dependencySourceIncludes>

                           <!-- Doclet for creating plantuml graphs inside the javadoc pages -->
                            <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
                            <docletArtifact>
                                <groupId>nl.talsmasoftware</groupId>
                                <artifactId>umldoclet</artifactId>
                                <version>2.0.9</version>
                            </docletArtifact>
                            <additionalOptions>
                                <!--<additionalOption>...</additionalOption> -->
                            </additionalOptions>

                        </configuration>

                        <executions>
                            <execution>
                                <id>profile-aggregate-javadoc</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

```

**Comment by devlauer** [comment]
Hi,

it is good to hear that you found a solution for your problem and that you are quite happy with it.
With your latest posts i also realized the original problem why your configuration did not work in your use case but why it worked in my use case in my sample project. We both have different use cases for our diagram creation:
* you wanted to have all classes of all **sub**packages of all modules in your diagram
* in my use case i only wanted to have all named packages of all modules in my diagram

To make your use case work you have to add another parameter to your configuration: whitelistRegexp with the value .* .In this case all subpackages and classes in all dependencies are scanned too. So if you change your config in your fhirstore-netty module to 
` <plugin>
                <artifactId>plantuml-generator-maven-plugin</artifactId>
                <groupId>de.elnarion.maven</groupId>
                <version>1.1.2</version>
                <executions>
                    <execution>
                        <id>generate-class-dependency-puml</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <outputFilename>${project.artifactId}-class-dependency.puml</outputFilename>
                            <scanPackages>
                                <scanPackage>
                                    at.pineit.fhirstore
                                </scanPackage>
                            </scanPackages>
                            <whitelistRegexp>.*</whitelistRegexp>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

your diagram will contain all classes from all subpackages of at.pineit.fhirstore from all modules.
Perhaps i should clarify this in the documentation.

Kind Regards

**Comment by arauchberger** [comment]
<whitelistRegexp>.*</whitelistRegexp>

that did the trick. Thanks
