### ISSUE TITLE
Class UML doesn't handle Collection or Map relationships

### ISSUE THREAD

**Issue by szetheli** [devlauer/plantuml-generator#67]
The UML generation handles List and Set types but not other forms of Iterable, such as Collection or Map types.  The check for addAggregationRelationship should try to use Iterable (the base class of all collections) instead of explicit checks for List and Set.

**Comment by devlauer** [comment]
Yes, you are right. I don't know anymore why it was limited to List and Set. 
I've extended the handling to Iterable and Map. The new release 2.1.0 will be available in the next hours as soon as it is distributed to maven central.
