### ISSUE TITLE
Maven plugin not work for many modules

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [devlauer/plantuml-generator#7]
I got maven module structure like this:

```
MyProject 
    --> application
    --> domain
    --> infrastructure
          --> infra.pom

parent.pom
```

I added this config to `infra.pom`

```
      <plugin>
        <artifactId>plantuml-generator-maven-plugin</artifactId>
        <groupId>de.elnarion.maven</groupId>
        <version>1.1.2</version>
        <executions>
          <execution>
            <id>generate-plantuml-diagram</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-test-sources</phase>
            <configuration>
              <outputFilename>plantuml_diagram.plantuml</outputFilename>
              <scanPackages>
<!--                <scanPackage>kkl.pausa.application</scanPackage>-->
                <scanPackage>kkl.pausa.infrastructure</scanPackage>
<!--                <scanPackage>kkl.pausa.domain</scanPackage>-->
              </scanPackages>
              <hideMethods>true</hideMethods>
              <hideFields>true</hideFields>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

a) when I run `install` goal and uncomment another packages located in different modules
    plant uml file will not be generated.

b) running this plugin with `site` goal from parent pom also not work

**Comment by devlauer** [comment]
Hi,

I hope I understood your problem and so i'm trying to answer:
a) the plugin searches for each "scanpackage" with the help of the classloader of the maven project (the pom.xml where you placed the plugin, in this case the infrastructure module). If the "scanpackage" can be found there it will be processed. If it can not be found there, it will not be processed and an ClassNotFoundException is thrown. 
So i guess that your infrastructure module does not have any dependency on your domain and/or application module and therefore the classloader of the infrastructure module does not have access to the packages kkl.pausa.application or kkl.pausa.domain which are located in this modules.
Just add these modules to your dependency list in your infrastructure module, run `mvn install` and it should work.
b) if you run `mvn site`, this is a different buildprocess with a different lifecycle, not like normal builds as `mvn install`. This lifecycle does not contain a `generate-test-source` phase and therefore this plugin will not be executed.
If you want to execute this plugin during site creation, you have to bind it to one of the lifecyle phases of the site lifecycle like 
* pre-site
* site
* post-site
* deploy
or you need to execute your defined lifecycle-phase (here generate-test-sources) before site creation: `mvn generate-test-sources site`

**Comment by devlauer** [comment]
Because there was no reply for more than two months, I think there is no demand for help anymore, so I will close this issue.
If you are still struggling with your problem, just reopen this issue or create a new one.
