### ISSUE TITLE
groovy

### ISSUE THREAD

**Issue by halilgithub** [devlauer/plantuml-generator#93]
Hello, tnx for your effort.
Does it work for groovy codebase ?

**Comment by devlauer** [comment]
Sorry for the late reply but I only got around to it now.  If the groovy class is compiled, it works too. Here is a small example where groovy classes become part of the plantuml diagram:
https://github.com/devlauer/sample.asciidoc/blob/master/project1/pom.xml
https://github.com/devlauer/sample.asciidoc/blob/master/project1/src/main/groovy/de/elnarion/sample/Student.groovy

**Comment by devlauer** [comment]
I close this issue. If you have any further questions on my example feel free to open it again.
